model:
  name: "meta-llama/Llama-3.1-8B-Instruct"
  pretrained_mlps: "/home/t84411738/github/gist_vs_details/checkpoints/Llama-3.1-8B-Instruct/meta_learned_mlps_llama_epoch11.pt" 

training:
  num_epochs: 1
  lr: 3e-2
  loss_func: "mse"  # "mse" or "cosine"
  optimizer: "sgd"  # "sgd" or "adam"

evaluation:
  target_percentages: [5, 25, 50, 75, 85, 90, 95, 100]
  num_generate_tokens: 16

data:
  splits: [512, 1024, 2048, 4096, 8192, 10000]
  num_samples_per_split: 100
